filter:
  excluded_paths: [vendor/*, tests/*]
checks:
  php:
    code_rating: true
    remove_extra_empty_lines: true
    remove_trailing_whitespace: true
    fix_identation_4spaces: true
    fix_doc_comments: true
tools:
  external_code_coverage: true