name: build

on: [push]

jobs:
  code-style:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v2.1.4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: cs-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: cs-composer-
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: PHP Code Style run
        run: vendor/bin/phpcs --standard=phpcs.xml
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '7.4', '8.0' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v2.1.4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php-versions }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php-versions }}-composer-
      - name: Install dependencies
        run: composer install --prefer-dist
      - name: PHPUnit run
        run: vendor/bin/phpunit --colors=always
  coverage:
    name: Tests coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: PHP setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: pcov
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v2.1.4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: 80-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: 80-composer-
      - name: Install dependencies
        run: composer install --no-progress --prefer-dist
      - name: PHPUnit run with coverage
        run: vendor/bin/phpunit --colors=always --coverage-clover=clover.xml
      - name: Upload coverage report
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: clover.xml
